### ISSUE TITLE
Improving the Footer

### ISSUE THREAD

**Issue by Shaba1406** [Prajwal0225/My-Favorite-SuperHero#182]
A footer can be More Attractive.

Could you Please assign it to me under Hacktoberfest 2023

**Comment by ChaitanyaLonarkar** [comment]
I made the footer attractive if you assign me this task then i can add pull request under hactoberfest 2023

**Comment by madhurafulkar** [comment]
Please provide a general idea of what you would like improve. @Shaba1406

**Comment by madhurafulkar** [comment]
https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/120560129/3c1c72eb-f2fe-47d0-b044-3ae5eb926e6a

Design a footer like this.

**Comment by divyansh-4** [comment]
Hi @madhurafulkar , I can get this done. Please assign it to me.

**Comment by ZainabR11** [comment]
@Prajwal0225 Can I work on this issue for hacktoberfest?

**Comment by Shaba1406** [comment]
you can assign this issue to someone else. as i am not free right now

**Comment by divyansh-4** [comment]
Hi @Prajwal0225 @madhurafulkar , I have created the footer as shown in the video above. However, I did not add the grey background, since I felt like it did not fit in with the overall theme.
Also, I noticed that the linkedin and twitter(x) icons re-directed to the home page. Do let me know in case that needs to be changed.
I have opened a pull request for this. Do let me know if any other changes are to be made. Thank You !

**Comment by Prajwal0225** [comment]
Nice Work @divyansh-4 ✨

**Comment by divyansh-4** [comment]
Thank you @Prajwal0225 
Also, I noticed that the about and contributors page does not have a footer. Would you like me to create a new issue for that, or maybe work on it ?

**Comment by Prajwal0225** [comment]
Ook, @divyansh-4  you can raise a PR regarding that.
It required only copy and pasting work so no need to create issue make a direct PR.

**Comment by divyansh-4** [comment]
HI @Prajwal0225 
I have created another PR for the about and contributors page. The background for the footer is grey for the contributors page, since the whole page was in grey. 
Kindly confirm if this issue has to be changes. Also, I noticed that the contributors page has a huge space in the bottom. I think we may have to create a seperate Issue for that.
I would also appreciate it if you could add the hacktober tag to that PR.
Thank You !
